

name: CD


on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:

  Deploy:
    
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: SSH into Host
        run: |
          ls
          scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:temp
  #        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /var/www/deploy.sh"
