# A workflow for running CI tests on the TileTown server application

name: CI

# CI tests should be triggered whenever we make a push, be that to
# main or the development branch. 

on: [workflow_call, workflow_dispatch, push, pull_request]

jobs:

  # First, we check that the project compiles/builds successfully
  Compile:
    # The type of machine we want our tests to run on - in this, the latest version of linux ubuntu
    runs-on: ubuntu-latest
    steps: 

      # Checkout the branch we want to run 
      - uses: actions/checkout@v3

      # 
      - name: Compile Test
        run: |
          npm --prefix server install
          npm --prefix server run build
          
  # Next, check if the unit tests are passing
  Test: 
    # Specify the operating system
    runs-on: ubuntu-latest
    
    # This is how we require that Test runs only if Compile is successful
    needs: Compile

    steps:

      # Checkout the branch
      - uses: actions/checkout@v3

      # Run the unit tests
      - name: Unit Tests
        run: |
          npm --prefix server install 
          npm --prefix server run test
